#ifndef _APP_H_
#define _APP_H_

typedef enum
{
	T1_EVENT_CAN_NOT_USE = GAPP_TASK_INITED,
	T1_UART_DATA_RECV_IND = 1,// uart data receive
	T1_SOCK_CONNECT_RSP = 2,
	T1_SOCK_ERROR_IND = 3,
	T1_SOCK_DATA_RECV_IND = 4,
	T1_SOCK_CLOSE_IND = 5,
	T1_SOCK_CLOSE_RSP = 6,
	T1_ASYN_PDP_ACTIVE_IND=7,	/*	20140812 luyong add for asyn pdp active	*/
	T1_ASYN_PDP_RELEASE_IND=8,	/*	20140812 luyong add for asyn pdp releasse	*/
	T1_TTS_END_IND = 9,
	T1_SEC_TIMER_IND = 10,
	T1_INIT_GAGENT = 11,
	T1_HB_TIMEOUT = 12
}APP_TASK1_EVENT_T;

typedef enum
{
	T2_EVENT_CAN_NOT_USE = GAPP_TASK_INITED,
	T2_EVENT_AT_RSP_IND = 1,// AT RESPONE
}APP_TASK2_EVENT_T;

typedef enum
{
	T3_EVENT_CAN_NOT_USE = GAPP_TASK_INITED,
    T3_CSQ_TIMER_IND = 1,
}APP_TASK3_EVENT_T;

typedef enum
{
	T4_EVENT_CAN_NOT_USE = GAPP_TASK_INITED,
}APP_TASK4_EVENT_T;

typedef enum
{
	T5_EVENT_CAN_NOT_USE = GAPP_TASK_INITED,
}APP_TASK5_EVENT_T;


extern UINT32 TASK_ONE,TASK_TWO,TASK_THREE,TASK_FOUR,TASK_FIVE;

#endif